### ISSUE TITLE
Failure build

### ISSUE THREAD

**Issue by umbrella-vladislav-pisarev** [redfox256/testcafe-reporter-reportportal#1]
I have issue at the end of executing tests:

`
16:05:04 49 passed (Duration: 4m 36s)
16:05:04 { error_code: 40025, message: "Start time of child ['Tue Feb 12 13:02:53 UTC 2019'] item should be same or later than start time ['Tue Feb 12 13:03:03 UTC 2019'] of the parent item/launch '5c62c4071aa841000161927c'" }
16:05:04 (node:29036) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
16:05:04 (node:29036) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
16:05:04 (node:29036) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
16:05:04 (node:29036) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
16:05:04 (node:29036) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
16:05:04 (node:29036) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)
16:05:04 (node:29036) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7)
`

The issue reproduced when `concurrency` in TestCafe config > 1

I use `TestCafe v.1.0.0`

**Comment by redfox256** [comment]
I am unable to reproduce the error using the latest version of `TestCafe v1.0.0` and the `concurrency` set to > 1

Can you confirm that it works when `.concurrency(1)`.
Would it be possible to send me a sample project?

**Comment by redfox256** [comment]
unable to produce issue.
