### ISSUE TITLE
Enhancement: Add Tags at runtime

### ISSUE THREAD

**Issue by kerly** [redfox256/testcafe-reporter-reportportal#11]
As a user, I'd like to add tags at runtime since certain tags are dynamic and can't be added to the configuration files.

Potential solutions:

1. Add tags through CLI
```
testcafe chrome path/to/tests --reporter reportportal --tags tag1,tag2
```
2. Add tags through environment variables
```
export RP_TAGS = tag1,tag2 # shell
$Env:RP_TAGS = tag1,tag2 # windows
```

If I can solve it, I'll put in a PR.

**Comment by kerly** [comment]
Nevermind, I see this is supported through the environment variable `REPORT_PORTAL_TAGS`. Maybe I'll just update the README to include this.

**Comment by iegor-zabielin** [comment]
@kerly but information regarding tags actually was added

<img width="869" alt="Screenshot at Jun 20 16-12-16" src="https://user-images.githubusercontent.com/32905475/59851860-4edc5f80-9376-11e9-8be7-93b99c40c0df.png">

**Comment by kerly** [comment]
Yes you're right, I'll close this
