### ISSUE TITLE
Launches aren't finishing

### ISSUE THREAD

**Issue by kerly** [redfox256/testcafe-reporter-reportportal#12]
I've noticed that the reporter isn't always reporting the launch as finished, so the reportportal thinks they are still running. When running a small number of tests this isn't happening, but over 10 tests it's happening consistently.   
Might be related to this: https://github.com/reportportal/reportportal/issues/543#issuecomment-449000010

**Comment by kerly** [comment]
When I pass the variable `debug: true` to the `rpClient`, I can see the logs. Sometimes the launch API calls aren't finished by the time testcafe shuts down the process so the finish command doesn't make it to reportportal.   

Doesn't finish launch
```
Success finish item sktwi1hh9jx3rw82r
Finish test item sktwi1hh9jx3rw088
✨  Done in 126.86s.
```

Looks like TestCafe plans to fix this in the next sprint, to be done by July 10th. https://github.com/DevExpress/testcafe/issues/3835

**Comment by kerly** [comment]
TestCafe have updated the `reportTaskDone` function to allow async awaits. This will solve the problem if we can add async await to the `reportTaskDone` calls in this library.   
I'm not able to add async await to this library because of some configurations needed with gulp-babel. I've tried multiple configurations with the `transform-runtime` plugin, but am unable to get it working properly. If anyone is able to assist in this effort it would be greatly appreciated!

**Comment by kerly** [comment]
I've updated this repository to utilize async await for `reportTaskDone`.  
Please review when you have the chance.  
https://github.com/redfox256/testcafe-reporter-reportportal/pull/15

**Comment by redfox256** [comment]
Thx @kerly, version 1.0.25 released
