### ISSUE TITLE
[Request] Can we get a link to the report portal dumped into the console?

### ISSUE THREAD

**Issue by nithinacv** [redfox256/testcafe-reporter-reportportal#18]
_Please consider this a feature request as I have been unable to do this myself by cloning/forking the repo._ 

I have noticed that if we could dump a link to the launch with each test run, it would make the test results (from Jenkins or an IDE) very accessible.

At the moment, in our setup, we have the tests running in Jenkins, but because the test results (screenshots and spec details) are logged in a separate place - i.e. Report Portal, there exists this extra step to now navigate to Report Portal and manually locate the run using various tricks - launch time, tag, launch name etc.

I feel we can provide a link to the launch - may be in the `finishLaunch()` part of the code, to alleviate this problem.

I tried to do it myself in the node_modules directory without cloning/forking the project. 
I am hoping someone will suggest a more elegant way.
This is what I did:
File: `node_modules/testcafe-reporter-reportportal/lib/productreport.js`
In `case 4:` of `finishLaunch()` at line ~182 in version 1.0.26 of this project, I updated the code in the `case` to this
```
case 4:
    context$2$0.next = 6;
    var res = _regeneratorRuntime.awrap(this.rpClient.finishLaunch(launchId, {
        end_time: this.rpClient.helpers.now()
    }));
    res.arg.promise.then((val) => {
        console.log('Report Portal launch: ' + val.link);
    });
    return res;
```

This provides a link in my CLI that looks like this:
![image](https://user-images.githubusercontent.com/72095121/111376741-3ba71280-8676-11eb-8c27-bed1cb9da74f.png)

I tried to do this by cloning the repo, but encountered a completely different `src/productreport.js` file instead of the `lib/productreport.js` I edited earlier.

**Comment by nithinacv** [comment]
I kinda figured out a way to do this and created this PR:
PR #19  Add ReportPortal Link To CLI at `finishLaunch()`

**Comment by redfox256** [comment]
Thanks for the PR, version `1.0.27` has been deployed
