### ISSUE TITLE
Enhancement. Set a LaunchName as an variable

### ISSUE THREAD

**Issue by dskochubey** [redfox256/testcafe-reporter-reportportal#2]
Hi. Is there any chance to set a LaunchName as a variable before run the tests? 
https://github.com/redfox256/testcafe-reporter-reportportal/blob/7223d3a60dd76c97804060c2a0d49f57299e92d9/src/productreport.js#L12

Currently it use a Project name. But it is not useful for example when I want to run tests against different Browsers and then in report portal filter by browser. 
For example, before run tests I set up a variable REPORT_PORTAL_LAUNCH_NAME=Tests-Chrome etc. Then in report portal I can create filers for widget by Chrome, FF, etc.

If it will work for you I'm able to do that modification and then open a PR. It is up to you.

**Comment by redfox256** [comment]
Hi @dskochubey 

I've implemented the change on the latest version `1.0.17`

**Comment by dskochubey** [comment]
Works good. Thx for quick response!
