### ISSUE TITLE
Exception occurs and launch items aren't added when tests are executed in parallel (-c) 

### ISSUE THREAD

**Issue by iegor-zabielin** [redfox256/testcafe-reporter-reportportal#3]
**STR:**
1. Spin up Report Portal locally.
2. Use **testcafe v.1.1.2.** (also tried on 0.23.3).
3. **Important** - prepare more than one js file with fixtures, each one should contain couple of tests.
4. Trigger parallel tests execution with -c 2 or -c 3 flag. 

**Errors in console are shown:** 
Error: Request failed with status code 406: {"error_code":40025,"message":"Start time of child ['Sat Apr 13 10:49:16 UTC 2019'] item should be same or later than start time ['Sat Apr 13 10:49:35 UTC 2019'] of the parent item/launch '5cb1bebfb3cb1f000162ca83'"}
    at axios.then.catch (/Users/izabielin/Documents/GitHub/fnn-portal/node_modules/reportportal-client/lib/rest.js:27:23)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Test launches results aren't added to the Report Portal.**

**_BTW:_** 
1. When more than 1 fixture and concurrency = 1 - everything is fine.
2. When 1 fixture and concurrency = 3 - everything is fine as well.

**Comment by iegor-zabielin** [comment]
@redfox256 i guess i found the place and fixed locally, however not sure to the end if this correct

<img width="768" alt="Screenshot at Apr 13 19-02-00" src="https://user-images.githubusercontent.com/32905475/56082402-2dfd0880-5e21-11e9-9e10-5e13b1e36b5b.png">

I removed testRunInfo.durationMs and added it here:
<img width="490" alt="Screenshot at Apr 13 19-21-17" src="https://user-images.githubusercontent.com/32905475/56082415-54bb3f00-5e21-11e9-87c0-6bc6e5ae9190.png">

**Comment by redfox256** [comment]
Hi iegor, thx i will take a look at your solution and test then push a new release

**Comment by iegor-zabielin** [comment]
that would be great!

**Comment by redfox256** [comment]
please test on the latest release `v1.0.18`

**Comment by iegor-zabielin** [comment]
Fixed, however duration of all tests on Report Portal is 0s. Something is incorrect still.

**Comment by iegor-zabielin** [comment]
<img width="672" alt="Screenshot at Apr 18 15-21-43" src="https://user-images.githubusercontent.com/32905475/56360551-b0a11180-61ed-11e9-91ec-756ee7cd8661.png">

**Comment by iegor-zabielin** [comment]
One more, fixture execution (and whole launch) never ends on Report Portal
<img width="617" alt="Screenshot at Apr 18 15-24-13" src="https://user-images.githubusercontent.com/32905475/56360708-1ee5d400-61ee-11e9-87b6-1409f313ad22.png">

**Comment by iegor-zabielin** [comment]
@redfox256 can you please take a look on this?

**Comment by redfox256** [comment]
`v1.0.19` released that includes the start/end times for the tests

**Comment by iegor-zabielin** [comment]
yes, much better. however, still something wrong with fixture duration on Report Portal:

I have launch which contains 2 fixtures inside:
- Fixture 1 (duration **1m 27s**):
  - Test 1 (duration 1m 20s);
  - Test 2 (duration 33s);
- Fixture 2 (duration **0.02s**):
  - Test 1 (duration 32s);
  - Test 2 (duration 28s);
  - Test 3 (duration 42s);
  - Test 4 (duration 39s);

**Comment by redfox256** [comment]
Please test on `v1.0.20`, has been added
