### ISSUE TITLE
Enhancement. Set a Tag as a variable

### ISSUE THREAD

**Issue by iegor-zabielin** [redfox256/testcafe-reporter-reportportal#5]
It will be very useful to provide possibility add tags as a variable before tests execution. You can put any additional information, which shouldn't be displayed in launch name.

I assume reportportal-js-client client provides such property.

<img width="609" alt="Screenshot at Apr 25 19-27-22" src="https://user-images.githubusercontent.com/32905475/56752076-2c700080-6790-11e9-9f4e-763f2abfc757.png">

**Comment by DmitryKochubey** [comment]
A `description` as a variable will be very useful too. For example into description put details about current launch.

**Comment by redfox256** [comment]
feel free to help add these enhancements by creating a feature and creating a pull-request.

**Comment by iegor-zabielin** [comment]
@redfox256 have created PR https://github.com/redfox256/testcafe-reporter-reportportal/pull/6

**Comment by iegor-zabielin** [comment]
@DmitryKochubey added description also in PR mentioned above

**Comment by redfox256** [comment]
@iegor-zabielin thanks for the contribution. `v1.0.21` has been released.
