### ISSUE TITLE
Enhancement. Do not track skipped tests

### ISSUE THREAD

**Issue by iegor-zabielin** [redfox256/testcafe-reporter-reportportal#8]
Skipped tests shouldn't be investigated

<img width="1000" alt="Screenshot at May 10 21-31-24" src="https://user-images.githubusercontent.com/32905475/58014794-4b00b780-7b02-11e9-9e97-cc132f5f6b1e.png">

**Comment by iegor-zabielin** [comment]
@redfox256 please take a look on created PR https://github.com/redfox256/testcafe-reporter-reportportal/pull/7

**Comment by redfox256** [comment]
pull request merged into `v1.0.22`
