### ISSUE TITLE
Enhancement: Do not show skipped tests as failed

### ISSUE THREAD

**Issue by kerly** [redfox256/testcafe-reporter-reportportal#9]
Currently the output of the CLI shows a red X for skipped tests.
[ ✖] Name of test that's being skipped

Ideally this could look different from an X, maybe a "-".
[ - ] Name of test that's being skipped

If I'm up to it I might put in a PR for this.

**Comment by kerly** [comment]
Here's a PR for this: https://github.com/redfox256/testcafe-reporter-reportportal/pull/10

**Comment by redfox256** [comment]
Thanks for the help @kerly.
Merge the change in a pushed to `v1.0.23`
